name: update-code-push
on: [push]
jobs:
  push-step-1:
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HUBADMIN_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace ### replace|ignore|fail; optional (defaults to fail) 
    - name: dev push to stage.cmkc.hubzero.org
      run: |
        echo "test 724"
        ssh hubadmin@stage.cmkc.hubzero.org "date >> /var/www/stage/drbtest.txt;"
