name: update-code-push
on: [push]
jobs:
  push-step-1:
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HUBADMIN_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: test cmd exec on stage.cmkc.hubzero.org
      run: |
        echo "test"
        ssh hubadmin@stage.cmkc.hubzero.org "date >> /var/www/dev/drbtest.txt;"
